2025-05-13 12:48:44,641 ERROR: Exception on / [GET] [in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py", line 86, in index
    return render_template('accueil.html')
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\accueil.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\base.html", line 50, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\accueil.html", line 18, in block 'content'
    <a href="{{ url_for('reset_password') }}" class="text-decoration-none text-muted">Mot de passe oublié ?</a>
    ^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password'. Did you mean 'scan_result' instead?
2025-05-13 12:48:44,656 ERROR: Erreur serveur: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py:307]
2025-05-13 12:48:45,269 ERROR: Exception on / [GET] [in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py", line 86, in index
    return render_template('accueil.html')
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\accueil.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\base.html", line 50, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^
  File "C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\templates\accueil.html", line 18, in block 'content'
    <a href="{{ url_for('reset_password') }}" class="text-decoration-none text-muted">Mot de passe oublié ?</a>
    ^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password'. Did you mean 'scan_result' instead?
2025-05-13 12:48:45,278 ERROR: Erreur serveur: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py:307]
2025-05-13 12:57:40,413 INFO: Démarrage de l'application [in C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py:71]
2025-05-13 12:57:56,902 ERROR: Erreur de connexion: [Errno 11001] getaddrinfo failed [in C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py:123]
2025-05-13 12:57:58,135 ERROR: Erreur de connexion: [Errno 11001] getaddrinfo failed [in C:\MSPR\MSPR-6.1\MSPR-6.1-Nadim-Dev\MSPR-6.1-Nadim-Dev\python_file\app.py:123]
